server:
  port: 8081

spring:
  application:
    name: ms-backend

  datasource:
    url: jdbc:mysql://localhost:3306/cdr_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cdr-backend-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.cdr.backend.model
    topic:
      cdr: cdr-events

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: cdr-platform
  resource: ms-backend
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
