CREATE TABLE IF NOT EXISTS cdrs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    start_time DATETIME(6) NOT NULL,
    source VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    service VARCHAR(50) NOT NULL,
    cdr_usage INT NOT NULL
); 